---
title: RESTHeart Cloud - Getting Started
layout: docs-adoc
menu: cloud
liquid: true
---

Welcome to RESTHeart Cloud's interactive documentation! Configure your connection details below to see personalized examples throughout the documentation.

++++
<script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
<script src="/js/interactive-docs-config.js"></script>
{% include interactive-docs-config.html %}
++++

== Getting Started

Now that you've configured your connection details, you can follow along with the examples below. All code snippets will automatically use your configuration.

== Basic Operations

=== Creating a Database

==== cURL

Create a new database using cURL:

[source,bash]
----
curl -X PUT [INSTANCE-URL]/mydb \
  -H "Authorization: Basic [BASIC-AUTH]"
----

==== HTTPie

Create a new database using HTTPie:

[source,bash]
----
http PUT [INSTANCE-URL]/mydb \
  Authorization:"Basic [BASIC-AUTH]"
----

==== JavaScript

Create a new database using JavaScript:

[source,javascript]
----
const response = await fetch('[INSTANCE-URL]/mydb', {
  method: 'PUT',
  headers: {
    'Authorization': 'Basic [BASIC-AUTH]'
  }
});
----

=== Creating a Collection

==== cURL

Create a new collection using cURL:

[source,bash]
----
curl -X PUT [INSTANCE-URL]/mydb/mycollection \
  -H "Authorization: Basic [BASIC-AUTH]"
----

==== HTTPie

Create a new collection using HTTPie:

[source,bash]
----
http PUT [INSTANCE-URL]/mydb/mycollection \
  Authorization:"Basic [BASIC-AUTH]"
----

==== JavaScript

Create a new collection using JavaScript:

[source,javascript]
----
const response = await fetch('[INSTANCE-URL]/mydb/mycollection', {
  method: 'PUT',
  headers: {
    'Authorization': 'Basic [BASIC-AUTH]'
  }
});
----

=== Inserting Documents

==== cURL

Insert a document using cURL:

[source,bash]
----
curl -X POST [INSTANCE-URL]/mydb/mycollection \
  -H "Authorization: Basic [BASIC-AUTH]" \
  -H "Content-Type: application/json" \
  -d '{"name": "John", "age": 30}'
----

==== HTTPie

Insert a document using HTTPie:

[source,bash]
----
http POST [INSTANCE-URL]/mydb/mycollection \
  Authorization:"Basic [BASIC-AUTH]" \
  name="John" age:=30
----

==== JavaScript

Insert a document using JavaScript:

[source,javascript]
----
const response = await fetch('[INSTANCE-URL]/mydb/mycollection', {
  method: 'POST',
  headers: {
    'Authorization': 'Basic [BASIC-AUTH]',
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({
    name: 'John',
    age: 30
  })
});
----

=== Querying Documents

==== cURL

Query documents using cURL:

[source,bash]
----
curl -X GET "[INSTANCE-URL]/mydb/mycollection?filter={'age':{\$gt:25}}" \
  -H "Authorization: Basic [BASIC-AUTH]"
----

==== HTTPie

Query documents using HTTPie:

[source,bash]
----
http GET "[INSTANCE-URL]/mydb/mycollection" \
  Authorization:"Basic [BASIC-AUTH]" \
  filter=="{'age':{\$gt:25}}"
----

==== JavaScript

Query documents using JavaScript:

[source,javascript]
----
const filter = encodeURIComponent("{'age':{\$gt:25}}");
const response = await fetch(`[INSTANCE-URL]/mydb/mycollection?filter=${filter}`, {
  headers: {
    'Authorization': 'Basic [BASIC-AUTH]'
  }
});
----

== Advanced Operations

=== Bulk Operations

==== cURL

Perform bulk insert using cURL:

[source,bash]
----
curl -X POST [INSTANCE-URL]/mydb/mycollection \
  -H "Authorization: Basic [BASIC-AUTH]" \
  -H "Content-Type: application/json" \
  -d '[
    {"name": "Alice", "age": 25},
    {"name": "Bob", "age": 35},
    {"name": "Charlie", "age": 28}
  ]'
----

==== HTTPie

Perform bulk insert using HTTPie:

[source,bash]
----
echo '[
  {"name": "Alice", "age": 25},
  {"name": "Bob", "age": 35},
  {"name": "Charlie", "age": 28}
]' | http POST [INSTANCE-URL]/mydb/mycollection \
  Authorization:"Basic [BASIC-AUTH]" \
  Content-Type:application/json
----

==== JavaScript

Perform bulk insert using JavaScript:

[source,javascript]
----
const documents = [
  {name: 'Alice', age: 25},
  {name: 'Bob', age: 35},
  {name: 'Charlie', age: 28}
];

const response = await fetch('[INSTANCE-URL]/mydb/mycollection', {
  method: 'POST',
  headers: {
    'Authorization': 'Basic [BASIC-AUTH]',
    'Content-Type': 'application/json'
  },
  body: JSON.stringify(documents)
});
----

=== Aggregation Pipeline

==== cURL

Run an aggregation pipeline using cURL:

[source,bash]
----
curl -X POST [INSTANCE-URL]/mydb/mycollection/_aggrs/pipeline \
  -H "Authorization: Basic [BASIC-AUTH]" \
  -H "Content-Type: application/json" \
  -d '[
    {"$group": {"_id": null, "avgAge": {"$avg": "$age"}}},
    {"$project": {"_id": 0, "averageAge": "$avgAge"}}
  ]'
----

==== HTTPie

Run an aggregation pipeline using HTTPie:

[source,bash]
----
echo '[
  {"$group": {"_id": null, "avgAge": {"$avg": "$age"}}},
  {"$project": {"_id": 0, "averageAge": "$avgAge"}}
]' | http POST [INSTANCE-URL]/mydb/mycollection/_aggrs/pipeline \
  Authorization:"Basic [BASIC-AUTH]" \
  Content-Type:application/json
----

==== JavaScript

Run an aggregation pipeline using JavaScript:

[source,javascript]
----
const pipeline = [
  {$group: {_id: null, avgAge: {$avg: '$age'}}},
  {$project: {_id: 0, averageAge: '$avgAge'}}
];

const response = await fetch('[INSTANCE-URL]/mydb/mycollection/_aggrs/pipeline', {
  method: 'POST',
  headers: {
    'Authorization': 'Basic [BASIC-AUTH]',
    'Content-Type': 'application/json'
  },
  body: JSON.stringify(pipeline)
});
----
