---
title: Plugins
layout: docs-adoc
---

== Introduction

RESTHeart works *out-of-the-box* by merely installing and configuring it.

It comes with a complete MongoDB API and a security implementation that allows to authenticate users and authorize requests according to a role-based policy.

These functionalities are actually provided by the standard plugins that are distributed with RESTHeart. If you look at the `./plugins` directory you'll find them:

[source,bash]
----
plugins
├── restheart-graphql.jar
├── restheart-mongodb.jar
├── restheart-polyglot.jar
└── restheart-security.jar
----

On the other side, real applications often need the API to be extended in some way.

Plugins allow to extend RESTHeart:

- **Services** extend the API adding web services.
- **Interceptors** snoop and modify requests and responses at different stages of the request lifecycle.
- **Initializers** execute initialization logic at system startup time.

It is also possible developing security plugins to customize the security layer. Refer to link:/docs/plugins/security-plugins[Develop Security Plugins] for more information.

In short, you can develop plugins in Java, Kotlin and JavaScript and deploy them in RESTHeart. For more information on how to deploy plugins refer to link:/docs/plugins/deploy[How to deploy Plugins].

IMPORTANT: Have a look at the link:https://github.com/SoftInstigate/restheart/tree/master/examples[plugin examples] for some code examples.

== The Plugin Skeleton Repository

To quick start a new plugin, you can clone the link:https://github.com/SoftInstigate/restheart-plugin-skeleton[plugin skeleton repository].

[source,bash]
----
$ git clone git@github.com:SoftInstigate/restheart-plugin-skeleton.git
$ cd restheart-plugin-skeleton
$ ./mvnw clean package
$ ./bin/restart.sh -p restheart
----

The script `./bin/restart.sh` automatically deploys the plugin and start RESTHeart with it. At first run, it also automatically downloads the latest version of RESTHeart.

IMPORTANT: check the repository link:https://github.com/SoftInstigate/restheart-plugin-skeleton/blob/master/README.md[README.md] for more information.

== The Proxy pattern

If you are not familiar with java, there is a different approach that can help you extending the API using the link:/docs/proxy[proxying] feature.

You can add a side microservice, for instance using NodeJs, that implements a Web Service. This microservice can execute requests to RESTHeart if it needs to read or write data to MongoDB.

You can then proxy it via RESTHeart so that it is protected under the same security domain of RESTHeart.

Add the following section to the `restheart.yml` configuration file to proxy call to the RESTHeart's URI `/anything` to the web resource `https://httpbin.org/anything`

[source,yml]
----
proxies:
   - location: /anything
     proxy-pass: https://httpbin.org/anything
     name: anything
----
