---
title: Collection Indexes
menu: mongodb
layout: docs-adoc
---

=== List the collection indexes

To list the collection indexes use the following request:

[source,http]
----
GET /inventory/_indexes HTTP/1.1
----

[source,json]
----
[
    {
        "v": 2,
        "key": {
            "_id": 1
        },
        "ns": "restheart.inventory",
        "_id": "_id_"
    }
]
----

=== Create an index

To create an index you have to specify the keys and the index options:

[source,json]
----
{ "keys":  <keys>, "ops": <options> }
----

[.text-primary]
**Example - create an unique, sparse index on property 'qty'**

To create an unique, sparse index on property `qty` run the following:

[source,http]
----
PUT /inventory/_indexes/qtyIndex HTTP/1.1

{"keys": {"qty": 1},"ops": {"unique": true, "sparse": true }}
----

[NOTE]
====
See also Indexes in MongoDB documentation
https://docs.mongodb.com/manual/indexes/
====

[.text-primary]
**Example - create a text index on property 'item'**

To create a text index on property `item` run the following:

[source,http]
----
PUT /inventory/_indexes/itemTextIndex HTTP/1.1

{ "keys": { "item": "text" } }
----

=== Delete an index

To delete an index use the following request:

[source,http]
----
DELETE inventory/_indexes/qtyIndex HTTP/1.1
----

=== Notes

When creating an index the index options must be valid.

An example of invalid options is specifying the attribute _unique_ on a
property that is not actually unique; in this case the response will
be 406:

[source,http]
----
HTTP/1.1 406 Not Acceptable

{
    "_exceptions": [
        {
            "exception": "com.mongodb.DuplicateKeyException",
            "exception message": "Write failed with error code 11000 and error message 'E11000 duplicate key error index: test.coll.$name2 dup key: ...."
        }
    ],
    "http status code": 406,
    "http status description": "Not Acceptable",
    "message": "error creating the index",
    ...
}
----

=== Indexes cannot be updated

To update an index, it must be **deleted** and **recreated**:

Trying to update an existing index returns 406 Not Acceptable.
