---
title: Write Requests
layout: docs-adoc
---

:page-liquid:

== Introduction

You will learn how to insert, update and delete documents in a collection.

{% include running-examples.adoc %}

== Write Mode

The default write modes for each HTTP verb are:

- `POST` verb has *insert* write mode
- `PUT` and `PATCH` verbs have *update* write mode

*Use `POST` to _create_ a document, `PUT` to _replace_ an existing document and `PATCH` to _update_ selected properties of an existing document.*

The query parameter `?wm=insert|update|upsert` allows specifying the **w**rite **m**ode.

IMPORTANT: *the qparam `?wm` is forbidden by default*; to allow it, the following permission must be granted to the client (the default user `admin` can use it because it has the `root` role that provides all permissions).

[source,json]
----
{
    "_id": "user-can-wse-wm-qparam",
    "roles": [ "user" ],
    "predicate": "path-prefix(/collection)",
    "mongo": {
        "allowWriteMode": true
    }
}
----

## Create a document

To create a document use the `POST` method.

++++
{% include code-header.html
    type="Request"
    link="http://restninja.io/share/fcf2a3da225dc2018581416fee19f96fb105cca3/6"
%}
++++


[source,http]
----
POST /inventory HTTP/1.1

{ "_id": "newItem",  "item": "rubber", "qty": 15, "size": { "h": 2, "w": 1, "uom": "cm" }, "status": "A" }
----

NOTE: If `_id` field is not specified in the request body, it will generated by MongoDB as an `ObjectId` and returned to the client via the `Location` response header.

== Replace a document

To replace a document use the `PUT` method.

++++
{% include code-header.html
    type="Request"
    link="http://restninja.io/share/21de47ede7d9e910b80ac0d998184bf992b98895/6"
%}
++++

[source,http]
----
PUT /inventory/newItem?wm=insert HTTP/1.1


{ "item": "pencil", "qty": 55, "size": { "h": 10, "w": 0.5, "uom": "cm" }, "status": "B", "suppliers": ["brand_1", "brand_2", "brand_3"] }
----

## Update a document's property

To update one or more properties of a document use the `PATCH` method.

++++
{% include code-header.html
    type="Request"
    link="http://restninja.io/share/cad8a808b52787063c7544d396d7b4ba30be489f/0"
%}
++++

[source,http]
----
PATCH /inventory/newItem HTTP/1.1

{ "status": "A" }
----

NOTE: the `PATCH` verb allows passing update operator expressions; the body can contain update operators.

## DELETE a document

To delete a document use the `DELETE` method.

++++
{% include code-header.html
    type="Request"
    link="https://restninja.io/share/c83643990fe2ba9857d267d9203445fd4a5ecef5/0"
%}
++++

[source,http]
----
DELETE /inventory/newItem HTTP/1.1
----

== Dot Notation

RESTHeart always allows using the dot notation to access the elements of an array and to access the fields of an embedded document.

The dot notation can be used in `PUT`, `PATCH` and `POST` verbs.

=== Update an array element

++++
{% include code-header.html
    type="Request"
    link="http://restninja.io/share/d891c0dfaf794019f7cebf79dafa895cd9697da7/0"
%}
++++

[source,http]
----
PATCH /inventory/newItem HTTP/1.1

{ "suppliers.1": "new_brand" }
----

==== Update the property of an embedded document

++++
{% include code-header.html
    type="Request"
    link="http://restninja.io/share/fef0424bf8e69d11a7aae35f41a82e67164a1dfc/0"
%}
++++


[source,http]
----
PATCH /inventory/newItem HTTP/1.1

{ "size.h": 20 }
----

== Update Operators

Refer to MongoDB link:https://docs.mongodb.org/manual/reference/operator/update/[Update
Operators] documentation
for more information.

IMPORTANT: RESTHeart allows to use all MongoDB update operators on `PATCH` requests. `PUT` and `POST` can only use `$currentDate` update operator.

=== Apply given update operators to "newItem" document

++++
{% include code-header.html
    type="Request"
    link="http://restninja.io/share/1f3c2941dc649dfb8a3ba6628451093f83d02fea/0"
%}
++++

[source,http]
----
PATCH /inventory/newItem HTTP/1.1

{
  "$inc": { "qty": 1 },
  "$push": { "suppliers": "pushed_brand" },
  "$unset": { "status": null },
  "$currentDate": { "timestamp": true }
}
----

== Bulk Write Requests

Bulk write requests create, update or delete multiple documents with a
single request.

A bulk request response contains the URIs of the created documents.

IMPORTANT: *bulk requests are forbidden by default*; to allow them, the following permission must be granted to the client (the default user `admin` can execute them because it has the `root` role that provides all permissions):

[source,json]
----
{
    "_id": "user-can-execute-bulk-requests",
    "roles": [ "user" ],
    "predicate": "path-prefix(/collection)",
    "mongo": {
      "allowBulkPatch": true,
      "allowBulkDelete": true,
      "allowWriteMode": true
    }
}
----

=== Create an array of documents

++++
{% include code-header.html
    type="Request"
    link="http://restninja.io/share/cf5cba6e1d391b475e04c33d01715b883e1a5490/0"
%}
++++


[source,http]
----
POST /inventory HTTP/1.1

[
   { "item": "journal", "qty": 25, "size": { "h": 14, "w": 21, "uom": "cm" }, "status": "A" },
   { "item": "notebook", "qty": 50, "size": { "h": 8.5, "w": 11, "uom": "in" }, "status": "A" },
   { "item": "paper", "qty": 100, "size": { "h": 8.5, "w": 11, "uom": "in" }, "status": "D" },
   { "item": "planner", "qty": 75, "size": { "h": 22.85, "w": 30, "uom": "cm" }, "status": "D" },
   { "item": "postcard", "qty": 45, "size": { "h": 10, "w": 15.25, "uom": "cm" }, "status": "A" }
]
----

IMPORTANT: Its a `POST` request, then the default write mode is `insert`. As usual, you can use the `?wm=insert|update|upsert` query parameter to change write mode.

=== Update properties in multiple documents

++++
{% include code-header.html
    type="Request"
    link="http://restninja.io/share/0e5b13f1e048ea373f86c19e8fb48be7c70c7531/0"
%}
++++

[source,http]
----
PATCH /inventory/*?filter={"qty":{"$gte":50}} HTTP/1.1

{
  "qty":1000
}
----

=== DELETE multiple documents

++++
{% include code-header.html
    type="Request"
    link="http://restninja.io/share/acba248263a0be8e55ed03d7ff52e79a27449bbd/0"
%}
++++

[source,http]
----
DELETE /inventory/*?filter={"qty":{"$lte":50}} HTTP/1.1
----

== MongoDB write operations

The MongoDB write operation depends on the request method and on the write mode as follows:

[options="header"]
[cols="1,1,2,3,2"]
|============================================================================================
| write mode | method  | URI            | MongoDB write operation             | write operation argument
| *insert*   | *POST*  | `/coll`        | `insertOne`                         | *document*
| insert     | PUT     | `/coll/docid`  | `insertOne`                         | document
| insert     | PATCH   | `/coll/docid`  | `findOneAndUpdate(upsert:true)` (1) | update operator expression
| update     | POST    | `/coll`        | `findOneAndReplace(upsert:false)`   | document
| *update*   | *PUT*   | `/coll/docid`  | `findOneAndReplace(upsert:false)`   | *document*
| *update*   | *PATCH* | `/coll/docid`  | `findOneAndUpdate(upsert:false)`    | *update operator expression*
| upsert     | POST    | `/coll`        | `findOneAndReplace(upsert:true)`    | document
| upsert     | PUT     | `/coll/docid`  | `findOneAndReplace(upsert:true)`    | document
| upsert     | PATCH   | `/coll/docid`  | `findOneAndUpdate(upsert:true)`     | update operator expression
|============================================================================================

(1) uses a find condition that won't match any existing document, making sure the operation is an insert
