---
title: Examples of the WebSocket API
layout: docs-adoc
menu: mongodb
liquid: true
---

++++
<script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
<script src="/js/interactive-docs-config.js"></script>
{% include interactive-docs-config.html %}
++++

:page-liquid:

The following requests upsert a collection defining three change streams:

- *all* bound at `/messages/_streams/all`
- *mine* bound at `/messages/_streams/mine`

++++
<div x-data="requestTabs()">
  <div class="tab-buttons">
    <button @click="activeTab = 'curl'" :class="{'active': activeTab === 'curl'}" class="tab-button">cURL</button>
    <button @click="activeTab = 'httpie'" :class="{'active': activeTab === 'httpie'}" class="tab-button">HTTPie</button>
    <button @click="activeTab = 'javascript'" :class="{'active': activeTab === 'javascript'}" class="tab-button">JavaScript</button>
  </div>
  
  <div x-show="activeTab === 'curl'" class="tab-content">
++++

[source,bash]
----
curl -X PUT '[INSTANCE-URL]/messages' \
  -H 'Authorization: Basic [BASIC-AUTH]' \
  -H 'Content-Type: application/json' \
  -d '{
    "streams" : [
      { "stages" : [
          {
              "_$match": {
                "_$or" : [ { "operationType": "insert" }, { "operationType": "update" } ]
            }
          }
      ],
        "uri" : "all"
      },
      { "stages" : [
          { "_$match" : { "fullDocument::name" : { "_$var" : "n" } } }
        ],
        "uri" : "mine"
      }
    ]
}'
----

++++
  </div>
  
  <div x-show="activeTab === 'httpie'" class="tab-content">
++++

[source,bash]
----
echo '{
    "streams" : [
      { "stages" : [
          {
              "_$match": {
                "_$or" : [ { "operationType": "insert" }, { "operationType": "update" } ]
            }
          }
      ],
        "uri" : "all"
      },
      { "stages" : [
          { "_$match" : { "fullDocument::name" : { "_$var" : "n" } } }
        ],
        "uri" : "mine"
      }
    ]
}' | http PUT [INSTANCE-URL]/messages \
  'Authorization:Basic [BASIC-AUTH]' \
  'Content-Type:application/json'
----

++++
  </div>
  
  <div x-show="activeTab === 'javascript'" class="tab-content">
++++

[source,javascript]
----
fetch('[INSTANCE-URL]/messages', {
  method: 'PUT',
  headers: {
    'Authorization': 'Basic [BASIC-AUTH]',
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({
    "streams" : [
      { "stages" : [
          {
              "_$match": {
                "_$or" : [ { "operationType": "insert" }, { "operationType": "update" } ]
            }
          }
      ],
        "uri" : "all"
      },
      { "stages" : [
          { "_$match" : { "fullDocument::name" : { "_$var" : "n" } } }
        ],
        "uri" : "mine"
      }
    ]
  })
})
.then(response => response.json())
.then(data => console.log(data))
.catch(error => console.error('Error:', error));
----

++++
  </div>
</div>
++++

NOTE: The request body is included in the examples above.

Note that the `$match` stage specifies a condition on the `name` property using `fullDocument::name`.

This is because the Change Event looks like:

[source,json]
----
{
    "fullDocument": {
        "_id": { "$oid": "5e15ff5779ca449eb20fdd09" },
        "message": "hi uji, how are you?",
        "name": "uji",
        "_etag": { "$oid": "5e15ff57a2e5700c3459e801" }
    },
    "documentKey": {
        "_id": { "$oid": "5e15ff5779ca449eb20fdd09" }
    },
    "updateDescription": null,
    "operationType": "insert"
}
----

Note between the `_links` collection property the URIs of the
change streams (returned with `?rep=SHAL`).

++++
<div x-data="requestTabs()">
  <div class="tab-buttons">
    <button @click="activeTab = 'curl'" :class="{'active': activeTab === 'curl'}" class="tab-button">cURL</button>
    <button @click="activeTab = 'httpie'" :class="{'active': activeTab === 'httpie'}" class="tab-button">HTTPie</button>
    <button @click="activeTab = 'javascript'" :class="{'active': activeTab === 'javascript'}" class="tab-button">JavaScript</button>
  </div>
  
  <div x-show="activeTab === 'curl'" class="tab-content">
++++

[source,bash]
----
curl -X GET '[INSTANCE-URL]/messages?rep=SHAL' \
  -H 'Authorization: Basic [BASIC-AUTH]'
----

++++
  </div>
  
  <div x-show="activeTab === 'httpie'" class="tab-content">
++++

[source,bash]
----
http GET [INSTANCE-URL]/messages rep==SHAL \
  'Authorization:Basic [BASIC-AUTH]'
----

++++
  </div>
  
  <div x-show="activeTab === 'javascript'" class="tab-content">
++++

[source,javascript]
----
fetch('[INSTANCE-URL]/messages?rep=SHAL', {
  method: 'GET',
  headers: {
    'Authorization': 'Basic [BASIC-AUTH]'
  }
})
.then(response => response.json())
.then(data => console.log(data))
.catch(error => console.error('Error:', error));
----

++++
  </div>
</div>
++++

++++
{% include code-header.html type="Response" %}
++++

[source,json]
----
{
    "_links": {
        "all": {
            "href": "/messages/_streams/all"
        },
        "mine": {
            "href": "/messages/_streams/mine"
        }
    }
}
----

Alternatively, we can define a single change stream that either returns all messages or only those sent by a specific `name``. This can be achieved through a definition that utilizes optional stages:


[source,json]
----
{
    "streams" : [
{ "stages" : [
          { "$ifvar": [ "n", { "_$match" : { "fullDocument::name" : { "_$var" : "n" } } } ] }
        ],
        "uri" : "withOptionalStage"
      }
    ]
}
----

To subscribe to the change streams, we will use `websocat`, a Command-line client for WebSockets, like netcat (or curl) for `ws://`

TIP: You can install `websocat` following the instructions at link:https://github.com/vi/websocat#installation[] or downloading binaries from link:https://github.com/vi/websocat/releases[]

Connect to the change streams using the following command, given that the default user `admin` exists with the default password:

[source,bash]
$ websocat --text - autoreconnect:ws://admin:secret@127.0.0.1:8080/messages/_streams/all


To allow connections without authentication, you can define the following permission

++++
<div x-data="requestTabs()">
  <div class="tab-buttons">
    <button @click="activeTab = 'curl'" :class="{'active': activeTab === 'curl'}" class="tab-button">cURL</button>
    <button @click="activeTab = 'httpie'" :class="{'active': activeTab === 'httpie'}" class="tab-button">HTTPie</button>
    <button @click="activeTab = 'javascript'" :class="{'active': activeTab === 'javascript'}" class="tab-button">JavaScript</button>
  </div>
  
  <div x-show="activeTab === 'curl'" class="tab-content">
++++

[source,bash]
----
curl -X POST '[INSTANCE-URL]/acl' \
  -H 'Authorization: Basic [BASIC-AUTH]' \
  -H 'Content-Type: application/json' \
  -d '{
    "_id": "unauthenticatedCanConnectToMyWebSocket",
    "predicate": "path-prefix('"'"'/messages/_streams/all'"'"')",
    "priority": 0,
    "roles": [ "$unauthenticated" ]
}'
----

++++
  </div>
  
  <div x-show="activeTab === 'httpie'" class="tab-content">
++++

[source,bash]
----
echo '{
    "_id": "unauthenticatedCanConnectToMyWebSocket",
    "predicate": "path-prefix('"'"'/messages/_streams/all'"'"')",
    "priority": 0,
    "roles": [ "$unauthenticated" ]
}' | http POST [INSTANCE-URL]/acl \
  'Authorization:Basic [BASIC-AUTH]' \
  'Content-Type:application/json'
----

++++
  </div>
  
  <div x-show="activeTab === 'javascript'" class="tab-content">
++++

[source,javascript]
----
fetch('[INSTANCE-URL]/acl', {
  method: 'POST',
  headers: {
    'Authorization': 'Basic [BASIC-AUTH]',
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({
    "_id": "unauthenticatedCanConnectToMyWebSocket",
    "predicate": "path-prefix('/messages/_streams/all')",
    "priority": 0,
    "roles": [ "$unauthenticated" ]
  })
})
.then(response => response.json())
.then(data => console.log(data))
.catch(error => console.error('Error:', error));
----

++++
  </div>
</div>
++++

With this permission in place, you can connect to the WebSocket without authentication:

[source,bash]
$ websocat --text - autoreconnect:ws://127.0.0.1:8080/messages/_streams/all

If we now create a new document in the collection `messages`

++++
<div x-data="requestTabs()">
  <div class="tab-buttons">
    <button @click="activeTab = 'curl'" :class="{'active': activeTab === 'curl'}" class="tab-button">cURL</button>
    <button @click="activeTab = 'httpie'" :class="{'active': activeTab === 'httpie'}" class="tab-button">HTTPie</button>
    <button @click="activeTab = 'javascript'" :class="{'active': activeTab === 'javascript'}" class="tab-button">JavaScript</button>
  </div>
  
  <div x-show="activeTab === 'curl'" class="tab-content">
++++

[source,bash]
----
curl -X POST '[INSTANCE-URL]/messages' \
  -H 'Authorization: Basic [BASIC-AUTH]' \
  -H 'Content-Type: application/json' \
  -d '{
    "message": "Hello WebSockets!",
    "name": "uji"
}'
----

++++
  </div>
  
  <div x-show="activeTab === 'httpie'" class="tab-content">
++++

[source,bash]
----
echo '{
    "message": "Hello WebSockets!",
    "name": "uji"
}' | http POST [INSTANCE-URL]/messages \
  'Authorization:Basic [BASIC-AUTH]' \
  'Content-Type:application/json'
----

++++
  </div>
  
  <div x-show="activeTab === 'javascript'" class="tab-content">
++++

[source,javascript]
----
fetch('[INSTANCE-URL]/messages', {
  method: 'POST',
  headers: {
    'Authorization': 'Basic [BASIC-AUTH]',
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({
    "message": "Hello WebSockets!",
    "name": "uji"
  })
})
.then(response => response.json())
.then(data => console.log(data))
.catch(error => console.error('Error:', error));
----

++++
  </div>
</div>
++++

We get the following output from `websocat`:

[source,bash]
----
$ websocat --text - autoreconnect:ws://admin:secret@127.0.0.1:8080/messages/_streams/all
{"fullDocument":{"_id":{"$oid":"62166d53ebdcd56455a1a7ab"},"message":"Hello WebSockets!","name":"uji","_etag":{"$oid":"62166d53ebdcd56455a1a7aa"}},"documentKey":{"_id":{"$oid":"62166d53ebdcd56455a1a7ab"}},"operationType":"insert"}
----