---
title: Configuration
layout: docs-adoc
---

== Update the `admin` password!

At first startup, RESTHeart initializes the user `admin`, with the default password `secret`. *This user can execute any request*.

WARNING: *YOU MUST UPDATE THE DEFAULT PASSWORD!* The role `admin` can execute any request as it is set as the `root` role in the `mongoAclAuthorizer` configuration.

To update it, run the following command:

[source,bash]
$ curl -u admin:secret -X PATCH localhost:8080/users/admin -H "Content-Type: application/json" -d '{ "password": "my-strong-password" }'

Refer to link:/docs/security/user-management/[User Management] for more information on how to create new users, roles and permissions.

== Default configuration

RESTHeart v7 has a default configuration and specifying a configuration file is not required. The following command runs RESTHeart with the link:https://github.com/SoftInstigate/restheart/blob/master/core/src/main/resources/restheart-default-config.yml[default configuration].

[source,bash]
$ java -jar restheart.jar

The following command prints the default configuration to the console.

[source,bash]
$ java -jar restheart.jar -t

You can generate a configuration file with:

[source,bash]
java -jar core/target/restheart.jar -t 2> restheart.yml

== Modify the configuration with the RHO env var

The environment variable `RHO` allows to modify and add any configuration option.

An example is:

[source,bash]
$ RHO='/mclient/connection-string->"mongodb://127.0.0.1";/mongo/mongo-mounts[1]/where->"/api"' java -jar restheart.jar

or even:

[source,bash]
$ RHO='/mclient/connection-string->"mongodb://127.0.0.1";/mongo/mongo-mounts[1]->{"where: "/api", "what": "mydb"}' java -jar restheart.jar

The following command with the `-c` option, prints the effective configuration, i.e. the default configuration with the `RHO` overrides applied.

[source,bash]
```
$ RHO='/core/name->"***** test *****"' java -jar restheart.jar -c

INFO o.r.configuration.Configuration - Overriding configuration parameters from RHO environment variable:
INFO o.r.configuration.Configuration - /core/name -> ***** test *****

core: {name: '***** test *****', plugins-directory: plugins, base-url: null, io-threads: 0,
  worker-threads: -1, requests-limit: 1000, buffer-size: 16364, direct-buffers: true,
  force-gzip-encoding: false, allow-unescaped-characters-in-url: true}
```
The format is:

[source,bash]
<xpath expression> -> JSON

So valid assignments are:

[source,bash]
/core/name->"production"
/mongo/mongo-mounts[1]->{"where": "/api", "what": "mydb"}
/core/io-threads->8

The following are invalid:

[source,txt]
/core/name->production                      # missing quotes in JSON value
/mongo/mongo-mounts[1]->{"where: "/api"     # invalid JSON object
core/io-threads->8                          # xpath expression does not start with /

== Configuration file

RESTHeart can also use a configuration file:

[source,bash]
$ java -jar restheart.jar -t 2> restheart.yml # create a configuration file with default values
$ java -jar restheart.jar restheart.yml

The configuration file can also be parametrized using the `{{{my-parameter}}}` notation. An example of a parametrized configuration file is link:https://github.com/SoftInstigate/restheart/blob/master/core/etc/restheart.yml[restheart.yml].

The parameters can be specified with a `.properties` file. An example of properties file is link:https://github.com/SoftInstigate/restheart/blob/master/core/etc/default.properties[default.properties]

[source,bash]
$ java -jar restheart.jar restheart.yml -e default.properties

== Change the configuration in Docker container

The configuration of RESTHeart running in a Docker container can be modified in two ways.

=== 1 - Using the `RHO` env variable

The following example uses the option `-e RHO="....."` to override the configuration parameters `/mclient/connection-string` and `/core/name`.

[source,bash]
----
$ docker run -d --rm  -p "8080:8080" -e RHO="/mclient/connection-string->'mongodb://host.docker.internal';/core/name->'the-best-api-ever'" softinstigate/restheart

INFO  o.r.configuration.Configuration - Overriding configuration parameters from RHO environment variable:
INFO  o.r.configuration.Configuration - 	/mclient/connection-string -> mongodb://host.docker.internal
INFO  o.r.configuration.Configuration - 	/core/name -> the-best-api-ever
.....
----

=== 2 - Using a configuration file

The following commands add a configuration file to the container:

[source,bash]
----
$ # generate the default configuration file in /tmp/restheart.yml (and edit it)
$ docker run --rm -p 8080:8080 -v /tmp/restheart.yml:/opt/restheart/etc/restheart.yml softinstigate/restheart -t 2> /tmp/restheart.yml

$ # run the RESTHeart container mounting the conf file as a volume
$ docker run --rm -p 8080:8080 -v /tmp/restheart.yml:/opt/restheart/etc/restheart.yml softinstigate/restheart etc/restheart.yml
----

Please note, that the Docker container still defines the following `RHO` variable which will override the parameters in the configuration file:

```
ENV RHO='/mclient/connection-string->"mongodb://host.docker.internal";/http-listener/host->"0.0.0.0"'
```

To avoid this, just specify your RHO overrides:

```
$ docker run --rm -p 8080:8080 -e RHO="/mclient/connection-string->'mongodb://host.docker.internal';"  -v /tmp/restheart.yml:/opt/restheart/etc/restheart.yml softinstigate/restheart etc/restheart.yml
```
