---
title: Setup
layout: docs-adoc
---

== Update the root user password!

At first startup, RESTHeart initializes the user `admin`, with default password `secret` that can execute any request.

INFO: The role `admin` can execute any request it is set as `root` role in the `mongoAclAuthorizer` configuration.

WARNING: *YOU MUST UPDATE THE DEFAULT PASSWORD!*

To update it, run the following command:

[source,bash]
$ curl -u admin:secret -X PATCH localhost:8080/users/admin -H "Content-Type: application/json" -d '{ "password": "my-strong-password" }'

== Configuration files

The main configuration file is link:https://github.com/SoftInstigate/restheart/blob/master/core/etc/restheart.yml[restheart.yml] which is parametrized using the `{{{my-parameter}}}` notation. The link:https://github.com/SoftInstigate/restheart/blob/master/core/etc/default.properties[default.properties] contains actual values for parameters defined into the YAML file. You pass these properties at startup, using the `-e` or `--envFile` parameter, like this:

[source,bash]
$ java -jar restheart.jar etc/restheart.yml -e etc/default.properties

TIP: To connect RESTHeart to a remote MongoDB instance you have to edit the `mongo-uri` property, setting you own link:https://docs.mongodb.com/manual/reference/connection-string/[Connection String]. For example, a MongoDB Atlas cluster connection string could be something like `mongodb+srv://<username>:<password>@cluster0.mongodb.net/test?w=majority`. Remember that RESTHeart internally uses the MongoDB Java driver, so you must follow that connection string format.

You have to restart the core `restheart.jar` process to reload a new configuration. How to stop and start the process depends on how it was started: either within a docker container or as a native Java process. In case of native Java, usually you have to kill the background `java` process but it depends on your operating system.

You can edit the YAML configuration file or create distinct properties file. Usually one set of properties for each deployment environment is a common practice.

== Environment variables

It is possible to override any primitive type parameter in `restheart.yml` with environment variables.

Primitive types are:

-   String
-   Integer
-   Long
-   Boolean

The  name of the shell environment variable is equal to a YAML parameter in `restheart.yml`, in uppercase and replacing `-` (dash) with `_` (underscore).

To avoid conflicts with other variables, the environment variable name can be prefixed with `RH_`, `RESTHEART_` or the legacy `RESTHEART_SECURITY_` .

For example, the parameter `mongo-uri` in the YAML file can be overridden by the `MONGO_URI` environment variable:

[source,bash]
$ MONGO_URI="mongodb://127.0.0.1" java -jar restheart.jar etc/restheart.yml -e etc/default.properties

TIP: Have a look at the link:https://github.com/SoftInstigate/restheart/blob/master/docker-compose.yml[docker-compose.yml] file for an example of how to export an environment variable if using Docker.

The following log entry appears at the very beginning of logs during the startup process:

[source,bash]
[main] WARN  org.restheart.Configuration - >>> Overriding parameter 'mongo-uri' with environment value 'MONGO_URI=mongodb://127.0.0.1'

WARNING: Environment variables replacement works only with primitive types: it doesn’t work with YAML structured data in configuration files, like arrays or maps. It's mandatory to use properties files and mustache syntax for that.

TIP: Watch link:https://www.youtube.com/watch?v=dzggm7Wp2fU&t=820s[Configuration] video.